export const initialTasks = [
  {
    id: "1",
    title: "Buy groceries",
    priority: "High",
    dueDate: "2024-09-15",
    description: "Buy bananas and apples",
    isCompleted: false,
  },
  {
    id: "2",
    title: "Finish project report",
    priority: "Medium",
    dueDate: "2024-08-26",
    description: "Calculate the numbers",
    isCompleted: false,
  },
  {
    id: "3",
    title: "Gym workout",
    priority: "Low",
    dueDate: "2024-07-12",
    isCompleted: false,
  },
  {
    id: "4",
    title: "Call plumber",
    priority: "High",
    dueDate: "2024-10-14",
    isCompleted: false,
  },
  {
    id: "5",
    title: "Schedule dentist appointment",
    priority: "Medium",
    dueDate: "2024-12-16",
    isCompleted: false,
  },
  {
    id: "6",
    title: "Prepare presentation",
    priority: "High",
    dueDate: "2024-09-17",
    isCompleted: false,
  },
  {
    id: "7",
    title: "Plan weekend trip",
    priority: "Low",
    dueDate: "2024-09-18",
    isCompleted: false,
  },
  {
    id: "8",
    title: "Organize closet",
    priority: "Medium",
    dueDate: "2024-09-19",
    isCompleted: false,
  },
  {
    id: "9",
    title: "Read a book",
    priority: "Low",
    dueDate: "2024-10-20",
    isCompleted: false,
  },
  {
    id: "10",
    title: "Update software",
    priority: "Medium",
    dueDate: "2024-12-21",
    isCompleted: false,
  },
];
